services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\StripeBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaStripeBundle.php'
